spring:
  application:
    name: mail

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: mail
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  mail:
    host: smtp.gmail.com
    port: 587
    username: tecnhartstest@gmail.com
    password: fmhkefgsfoypeagl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka